### ISSUE TITLE
'nother resource bug

### ISSUE THREAD

**Issue by jsteele15** [preatomicprince/sturdy-waffle#16]
- when you place a stone mine it takes 100 stone off as a cost, when it should be set to minus wood
- when you change the bc.res_cost for the house (below) it actually changes the cost of building a stone mine
- if building_type[b_type] == "House":
            texture = "./res/house.png"
            self.bc.res["Pop. "] = 10000
            self.bc.res_cost["Stone"] = 50 (<====== this bit here)

**Comment by preatomicprince** [comment]
Fixed
